name: Test
permissions:
  contents: read
on:
  pull_request:
  push:
  workflow_dispatch:
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install Nix
      uses: cachix/install-nix-action@v31
      with:
        github_access_token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Cachix cache
      uses: cachix/cachix-action@v14
      with:
        name: mcp-selenium-haskell
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
    - name: Build everything
      run: nix build --accept-flake-config
    # - name: Run checks
    # run: nix flake check
